import type { Href } from 'expo-router';

/**
 * Every in-app destination, built in one place.
 *
 * Typed routes are enabled (`experiments.typedRoutes`) and `.expo/types/router.d.ts` is
 * regenerated by `expo start`. Paths are built as plain strings and asserted to `Href` — the
 * documented escape hatch for computed paths — so the app type-checks both before and after
 * that generated file is refreshed. Keep route strings here rather than inline in screens.
 */
function href(path: string): Href {
  return path as Href;
}

export const routes = {
  shop: href('/'),
  cart: href('/cart'),
  orders: href('/orders'),
  account: href('/account'),
  login: href('/login'),
  register: href('/register'),
  quoteRequest: href('/quote-request'),
  product: (slug: string): Href => href(`/product/${encodeURIComponent(slug)}`),
  order: (id: string): Href => href(`/orders/${encodeURIComponent(id)}`),
} as const;
