/**
 * Compile-time contract test: the enums published to clients by @topflow/shared must be
 * identical to the database enums generated by Prisma. Changing one without the other
 * breaks `tsc` — drift is caught in CI, not in production.
 */
import type * as Db from '@topflow/database';
import type * as Shared from '@topflow/shared';

type Equals<A, B> =
  (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2
    ? true
    : false;
type Assert<T extends true> = T;

export type EnumParity = [
  Assert<Equals<Db.Role, Shared.Role>>,
  Assert<Equals<Db.OrgRole, Shared.OrgRole>>,
  Assert<Equals<Db.OrgStatus, Shared.OrgStatus>>,
  Assert<Equals<Db.OrgType, Shared.OrgType>>,
  Assert<Equals<Db.PaymentTerms, Shared.PaymentTerms>>,
  Assert<Equals<Db.Emirate, Shared.Emirate>>,
  Assert<Equals<Db.TokenPurpose, Shared.TokenPurpose>>,
  Assert<Equals<Db.StockStatus, Shared.StockStatus>>,
  Assert<Equals<Db.UnitOfMeasure, Shared.UnitOfMeasure>>,
  Assert<Equals<Db.RfqStatus, Shared.RfqStatus>>,
  Assert<Equals<Db.QuotationStatus, Shared.QuotationStatus>>,
  Assert<Equals<Db.OrderChannel, Shared.OrderChannel>>,
  Assert<Equals<Db.OrderStatus, Shared.OrderStatus>>,
  Assert<Equals<Db.PaymentMethod, Shared.PaymentMethod>>,
  Assert<Equals<Db.PaymentStatus, Shared.PaymentStatus>>,
];
