/**
 * Writes the environment file of the production-like stack (docker-compose.prod.yml): random
 * database passwords and secrets, Supabase Auth keys signed with the stack's own JWT secret (the
 * legacy HS256 keys a self-hosted Supabase uses), and the public URLs derived from the ports.
 *
 *   node infra/compose/generate-env.mts [--https-port 8443] [--http-port 8080] [--mail-port 8025]
 *                                       [--db-port 5433] [--project topflow-hub] [--out infra/compose/.env] [--force]
 *
 * An existing file is never overwritten without --force: the database volume keeps the passwords it
 * was created with, so new ones would lock the stack out of its own data.
 */
import { createHmac, randomBytes } from 'node:crypto';
import { existsSync, realpathSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';

export interface StackOptions {
  project: string;
  httpsPort: number;
  httpPort: number;
  mailPort: number;
  dbPort: number;
  webHost: string;
  apiHost: string;
  authHost: string;
}

export const DEFAULTS: StackOptions = {
  project: 'topflow-hub',
  httpsPort: 8443,
  httpPort: 8080,
  mailPort: 8025,
  dbPort: 5433,
  // Browsers and curl resolve every *.localhost name to this machine; inside the stack the proxy
  // answers to the same names, so every client uses the same URLs.
  webHost: 'localhost',
  apiHost: 'api.localhost',
  authHost: 'auth.localhost',
};

type RandomSource = (size: number) => Buffer;

const base64url = (value: Buffer | string): string => Buffer.from(value).toString('base64url');

/** An HS256 JSON Web Token, as Supabase signs its legacy API keys. */
export function signJwt(payload: Record<string, unknown>, secret: string): string {
  const header = base64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const body = base64url(JSON.stringify(payload));
  const signature = createHmac('sha256', secret).update(`${header}.${body}`).digest('base64url');
  return `${header}.${body}.${signature}`;
}

export function publicUrl(host: string, port: number): string {
  return port === 443 ? `https://${host}` : `https://${host}:${port}`;
}

function checkPort(name: string, value: number): number {
  if (!Number.isInteger(value) || value < 1 || value > 65_535) {
    throw new Error(`${name} must be a port number between 1 and 65535, not ${value}.`);
  }
  return value;
}

/** Every variable docker-compose.prod.yml reads, in the order they are written. */
export function buildEnv(options: StackOptions, random: RandomSource = randomBytes, now: number = Date.now()): Map<string, string> {
  for (const [name, value] of Object.entries({
    '--https-port': options.httpsPort,
    '--http-port': options.httpPort,
    '--mail-port': options.mailPort,
    '--db-port': options.dbPort,
  })) {
    checkPort(name, value);
  }
  if (!/^[a-z0-9][a-z0-9_-]*$/.test(options.project)) {
    throw new Error('--project must be lower-case letters, digits, dashes or underscores (a Compose project name).');
  }

  const jwtSecret = base64url(random(48));
  const issuedAt = Math.floor(now / 1000);
  const expiresAt = issuedAt + 5 * 365 * 24 * 3600;
  const apiKey = (role: 'anon' | 'service_role') => signJwt({ iss: 'supabase', role, iat: issuedAt, exp: expiresAt }, jwtSecret);

  return new Map([
    ['COMPOSE_PROJECT_NAME', options.project],
    ['IMAGE_TAG', 'local'],
    ['HTTPS_PORT', String(options.httpsPort)],
    ['HTTP_PORT', String(options.httpPort)],
    ['MAIL_PORT', String(options.mailPort)],
    ['DB_PORT', String(options.dbPort)],
    ['WEB_HOST', options.webHost],
    ['API_HOST', options.apiHost],
    ['AUTH_HOST', options.authHost],
    ['SITE_URL', publicUrl(options.webHost, options.httpsPort)],
    ['API_PUBLIC_URL', publicUrl(options.apiHost, options.httpsPort)],
    ['SUPABASE_URL', publicUrl(options.authHost, options.httpsPort)],
    ['POSTGRES_PASSWORD', random(24).toString('hex')],
    ['AUTH_DB_PASSWORD', random(24).toString('hex')],
    ['JWT_SECRET', jwtSecret],
    ['ANON_KEY', apiKey('anon')],
    ['SERVICE_ROLE_KEY', apiKey('service_role')],
    ['INTERNAL_API_SECRET', base64url(random(36))],
    ['SENTRY_DSN', ''],
  ]);
}

export function formatEnv(env: Map<string, string>): string {
  const lines = [
    '# Generated by infra/compose/generate-env.mts for docker-compose.prod.yml. Contains secrets:',
    '# never commit it. Regenerating it for an existing stack needs `docker compose down -v` first.',
  ];
  for (const [key, value] of env) {
    if (!/^[\w.:/@-]*$/.test(value)) throw new Error(`${key} contains characters that need quoting.`);
    lines.push(`${key}=${value}`);
  }
  return `${lines.join('\n')}\n`;
}

function main(argv: string[]): void {
  const { values } = parseArgs({
    args: argv,
    options: {
      'https-port': { type: 'string' },
      'http-port': { type: 'string' },
      'mail-port': { type: 'string' },
      'db-port': { type: 'string' },
      project: { type: 'string' },
      out: { type: 'string', default: 'infra/compose/.env' },
      force: { type: 'boolean', default: false },
    },
    strict: true,
  });
  const out = values.out;
  if (existsSync(out) && !values.force) {
    throw new Error(`${out} already exists. Keep it, or run \`docker compose down -v\` and pass --force to start over.`);
  }
  const port = (value: string | undefined, fallback: number) => (value === undefined ? fallback : Number(value));
  const env = buildEnv({
    ...DEFAULTS,
    project: values.project ?? DEFAULTS.project,
    httpsPort: port(values['https-port'], DEFAULTS.httpsPort),
    httpPort: port(values['http-port'], DEFAULTS.httpPort),
    mailPort: port(values['mail-port'], DEFAULTS.mailPort),
    dbPort: port(values['db-port'], DEFAULTS.dbPort),
  });
  writeFileSync(out, formatEnv(env), { mode: 0o600 });
  console.log(`Wrote ${out}. The web app will be at ${env.get('SITE_URL')}.`);
}

const invokedDirectly = process.argv[1] !== undefined && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url));
if (invokedDirectly) {
  try {
    main(process.argv.slice(2));
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  }
}
